### ISSUE TITLE
Provider contract (v0) and the Kubernetes Infra Provider

### ISSUE THREAD

**Issue by sasiruLK** [sasiruLK/tinycloud-platform#1]
## Problem Statement

TinyCloud only runs on the Substrate it was built on. Core reads infrastructure
state by calling the Oracle Cloud SDK in-process, holds Oracle credentials
itself, and ships a tenancy's identifiers as built-in defaults — so a stranger
who deploys TinyCloud on their own cluster gets a dashboard that either fails or
quietly asks Oracle about someone else's account.

Nobody outside the project can add support for another Substrate. Doing so means
forking Core and writing Go, because the only extension point is a set of
unexported in-process interfaces. That makes the project a personal lab that
happens to be readable, rather than a platform anyone can run.

## Solution

Core stops talking to any cloud. Every vendor-specific capability moves behind a
**Provider**: an independent HTTP service that implements a published contract
and holds the credentials for its own Substrate. Core discovers Providers from
explicit configuration and reads from them over HTTP.

This spec delivers the contract and the first Provider kind:

- A published `/v0` OpenAPI contract for the **Infra** Provider kind, with one
  endpoint per Capability plus a Capability-discovery endpoint.
- A Provider server that hosts in-tree Provider implementations over that
  contract, so Core speaks HTTP to its own Providers exactly as it would to a
  third party's.
- A **Kubernetes Infra Provider**, serving a Snapshot from the Kubernetes API
  and metrics-server alone, with no cloud account of any kind.
- A **Conformance suite** that runs the full contract against any Provider URL
  and reports pass or fail per Capability.

The Kubernetes Provider is also the test of whether the architecture is real. If
a Snapshot cannot be assembled from the Kubernetes API, the existing interfaces
were Oracle-shaped after all, and the contract must change before it is
published rather than after.

## User Stories

1. As an Instance operator, I want to deploy TinyCloud on a cluster with no
   cloud account, so that I can evaluate it before committing to a Substrate.
2. As an Instance operator, I want the dashboard to show my nodes out of the
   box, so that a fresh install looks like a working product rather than an
   error page.
3. As an Instance operator, I want Core to hold no cloud credentials, so that
   compromising the API does not expose my Substrate.
4. As an Instance operator, I want each Provider to hold only its own
   Substrate's credentials, so that the blast radius of a bad Provider is
   bounded to one Substrate.
5. As an Instance operator, I want to list my Providers in configuration, so
   that I can see at a glance where my dashboard's data comes from.
6. As an Instance operator, I want a Provider I have not configured to be
   absent rather than fatal, so that a partial setup still renders.
7. As an Instance operator, I want Capabilities a Provider does not implement to
   appear as named warnings, so that I can tell "not supported" from "broken".
8. As an Instance operator, I want a Provider that is down to leave the last
   good Snapshot on screen marked stale, so that a restart does not blank my
   dashboard.
9. As an Instance operator, I want a slow Provider to be bounded by a timeout,
   so that one degraded Substrate cannot hang the whole view.
10. As an Instance operator, I want Core to reach Providers only over an
    authenticated connection, so that anything else in the cluster cannot query
    my infrastructure state.
11. As an Instance operator, I want Providers reachable only from Core by
    network policy, so that authentication is not the only control.
12. As an Instance operator, I want to rotate a Provider's token without
    redeploying Core, so that credential rotation is routine.
13. As an Instance operator running on Oracle Cloud, I want my existing
    dashboard to keep showing alarms, ingress, and backups, so that adopting
    Providers costs me no visible capability.
14. As an Instance operator, I want no tenancy identifiers baked into the
    published image, so that my deployment never contacts an account that isn't
    mine.
15. As a Provider author, I want a published OpenAPI contract, so that I can
    generate a client or server in my own language.
16. As a Provider author, I want to implement one Capability and still be
    useful, so that I do not have to stub endpoints I have no data for.
17. As a Provider author, I want a documented way to declare which Capabilities
    I serve, so that Core does not call endpoints I have not implemented.
18. As a Provider author, I want a Conformance suite I can run against my own
    service, so that I can prove it works before asking anyone to review it.
19. As a Provider author, I want the Conformance suite to report per Capability,
    so that a partial implementation gets a partial pass rather than a failure.
20. As a Provider author, I want the maintainers' own Providers to use the same
    contract, so that anything they can do, I can do.
21. As a Provider author, I want the contract versioned in the URL, so that I
    know when a change is expected to break me.
22. As a Provider author, I want to write a Provider in a language other than
    Go, so that I can use whatever my Substrate's SDK is best in.
23. As a maintainer, I want the contract to be the single source of truth for
    the Provider API documentation, so that the spec and the served
    documentation cannot drift apart.
24. As a maintainer, I want the Conformance suite to run against the in-tree
    Providers in CI, so that a contract change that breaks an implementation
    fails the build.
25. As a maintainer, I want Core to contain no vendor-named modules, so that the
    codebase matches the glossary's claim that Core is vendor-neutral.
26. As a maintainer, I want the Snapshot type to stay unchanged by this work, so
    that the UI needs no changes and the blast radius stays inside Core's read
    path.
27. As a contributor, I want to run TinyCloud and its default Provider locally
    against a local cluster, so that I can contribute without a cloud account.
28. As a TinyCloud user, I want the dashboard to look and behave exactly as it
    does today, so that this change is invisible except where it adds
    capability.

## Implementation Decisions

**The contract.** One endpoint per Capability of the Infra Provider kind —
instances, metric query, alarm statuses, ingress address, and backup objects —
plus a Capability-discovery endpoint listing what the Provider serves. Paths are
prefixed `/v0`. A Capability that a Provider does not implement returns `501`.
The contract is published as an OpenAPI document at the repository root and is
the source of truth: the Provider section of the served API documentation is
generated from it rather than hand-maintained alongside it.

**No stability promise at v0.** Per ADR-0001, the contract may change until a
second author has shipped a Provider against it. Breaking changes are announced
in the changelog; the version prefix moves to `/v1` only when a third-party
implementation exists.

**Wire types are the existing domain types.** The Snapshot, Node, Alarm,
Ingress, Backups, and Capacity shapes are already vendor-neutral and are used
unchanged as the contract's response bodies. This work introduces no new domain
vocabulary and no UI change.

**The seam is the existing source interfaces.** The five in-process source
interfaces consumed by the collector remain the only extension point inside
Core. The HTTP Provider client is one more implementation of them, so the
collector, the cache, the infra endpoint, and the UI are untouched. Nil-member
handling — a missing source is skipped and reported as a warning — is the
mechanism that renders an unimplemented Capability, so `501` maps onto behaviour
that already exists.

**Providers are declared in configuration.** A list of entries naming the
Provider kind, an identifier, a base URL, and a reference to the secret holding
its bearer token. No label-based discovery and no custom resource; per ADR-0001
that migration is additive and deferred until an operator needs to add a
Provider without changing configuration.

**Authentication is a bearer token per Provider**, supplied from a Kubernetes
secret, with default-deny network policy restricting Provider services to Core.
Mutual TLS is documented as a hardening option, not required, so that Provider
authors in any language need only set a header.

**Core's cloud module is renamed to a vendor-neutral name.** Types and
interfaces move unchanged. The built-in defaults carrying tenancy identifiers
are emptied; the existing override mechanism remains, and absent configuration
yields nil sources and warnings rather than a startup failure.

**In-tree Providers are served over the contract, not linked in.** Provider
implementations are written in Go against an internal interface and exposed by a
thin Provider server binary shipped in the same image. Core has exactly one code
path for reading infrastructure, and the maintainers' own Providers exercise the
public contract on every request.

**The Kubernetes Provider maps Capabilities as follows**: instances from the
node list; CPU and memory from metrics-server, degrading to absent values when
metrics-server is not installed; the ingress address from the ingress service's
external address. Alarms and backups return `501` — there is no cluster-native
equivalent, and reporting that honestly is the point of Capability discovery.
The Kubernetes client libraries are already dependencies; this adds none.

**Timeout and caching behaviour are unchanged.** Per-call timeouts continue to
bound each Capability call, and the existing cache — refresh on a TTL,
background refresh, last-good served and flagged stale past a threshold —
absorbs Provider latency and unavailability. Providers are polled on the cache's
schedule, not called per request.

**The Conformance suite is a distributable binary** taking a Provider URL and a
token, exercising every Capability, and reporting pass, fail, or not-implemented
per Capability, with a non-zero exit only on a genuine contract violation.

## Testing Decisions

**What makes a good test here.** Tests assert externally observable behaviour at
the highest available seam and say nothing about how it is produced. For this
work that means the served infra response — its shape, its stale flag, and the
named warnings — not the Provider client's methods, its request construction, or
its error types. A test that would fail if the HTTP client were rewritten but
the responses stayed identical is testing the implementation.

**Modules under test.**

- *The infra endpoint, driven end to end against a fake Provider.* An in-process
  HTTP test server stands in for a Provider; the assertions are on the response
  body — nodes present, metrics null when the Provider omits them, empty
  collections serialised as arrays, warnings naming each Capability that
  returned `501` or failed.
- *Degradation paths.* A Provider returning `501`, a Provider returning an
  error, a Provider that times out, and a Provider that is unreachable each
  produce a rendered Snapshot with the failure named, never an empty page or a
  panic. A previously good Snapshot survives a Provider outage and is flagged
  stale.
- *The Kubernetes Provider at its HTTP boundary*, backed by the fake Kubernetes
  clientset: node list to instances, metrics present and absent, ingress address
  present and pending, and `501` for the two unimplemented Capabilities.
- *The Conformance suite against the in-tree Providers*, run in CI, so that a
  contract change that breaks an implementation fails the build rather than
  being discovered by a Provider author.

**Prior art.** The existing infra handler test is the pattern to follow: it
drives the versioned infra route through an in-process HTTP test server, wires
one stub source and deliberately leaves the rest nil, then asserts on the
decoded envelope including that the sources which failed are named in the
warnings. The existing collector tests supply the partial-failure and JSON-shape
patterns — null values for missing metrics, empty collections as arrays — and
the cache tests already cover staleness and background refresh. The new tests
replace stub sources with a fake Provider over HTTP and otherwise assert the
same things.

## Out of Scope

- Porting the existing Oracle Cloud reads into an OCI Infra Provider. Separate
  spec, and deliberately sequenced after the Kubernetes Provider so the contract
  is proven against a second Substrate before the first is migrated.
- The Registry and Build Provider kinds, including extracting the hardcoded
  registry host.
- Secrets and ingress as Provider kinds. Per the design, these stay
  configuration rather than code.
- The Helm chart, the CLI, and its distribution.
- Custom-resource-based Provider discovery and mutual TLS between Core and
  Providers.
- Any change to the Snapshot shape, the UI, or the dashboard's behaviour.
- Licensing, README corrections, and archiving stale documentation.
- High availability, multi-region, and multi-tenant isolation, which are
  non-goals under ADR-0002.

## Further Notes

This work is a falsification test as much as a feature. If a Snapshot cannot be
served from the Kubernetes API alone, the source interfaces were shaped by
Oracle's SDK and the contract needs revising before publication — which is the
reason the contract ships as `/v0` with no stability promise, and the reason the
Kubernetes Provider is built before the Oracle one rather than after.

The security posture improves as a side effect: Core currently authenticates to
Oracle directly, and after this change holds no cloud credentials at all. The
new exposure is that a Provider runs in the operator's cluster holding that
Substrate's credentials, so documentation must state plainly that a third-party
Provider should be vetted like a chart from a stranger. See ADR-0001.

Terminology follows the project glossary: Core, Provider, Provider kind,
Capability, Substrate, Instance, and Snapshot are used as defined there.

**Comment by sasiruLK** [comment]
All seven children are closed; this is done on `providers-v0-contract` (5 commits), not yet merged.

**What shipped.** A published `/v0` OpenAPI contract at the repository root; a Provider server hosting the in-tree Providers over it, so Core has exactly one code path for reading infrastructure and the maintainers' own Providers exercise the public contract on every request; a Kubernetes Infra Provider needing no cloud account; and a Conformance suite that runs in CI. Core's cloud module is `internal/infra`, its tenancy defaults are empty, and the Snapshot, the API response and the UI are unchanged.

**The falsification test found something.** The metric source took an Oracle Monitoring namespace and an MQL query string. The Kubernetes Provider could not implement it, and neither could anyone else's. Contract metrics are named — `cpu.utilization` and four others, with contract dimension keys — and the Oracle reads translate at the edge. ADR-0003. That is the deviation from "the seam is the existing source interfaces", and it is the outcome #4 was written to produce.

**Known deviations**, each argued on its own issue: `internal/ocilog` is still vendor-named (#2), `/healthz` is unversioned (#3), and `collect_test.go` changed beyond a module rename (#2).

**Not verified against a live cluster.** Every "on a cluster with no cloud credentials" claim rests on the fake clientset and an in-process Provider.

**Two follow-ups this work earned:**

1. **Port the Oracle reads to an OCI Infra Provider.** Already scheduled as a separate spec, and the reason it matters more than it did: for an instance already on Oracle, enabling the Kubernetes Provider today makes the dashboard *worse* — a cluster knows two k3s nodes where Oracle knows four machines, and Traefik's node address where Oracle knows the load balancer's public IP. Core takes each Capability from the first Provider that declares it, ahead of the in-process fallback. Until the Oracle reads are a Provider too, the maintainer's instance ships with the Kubernetes Provider written but deliberately not enabled.
2. **A per-entry capability filter**, so an operator can take some Capabilities from a Provider and leave others. It is what would make (1) unnecessary as a prerequisite.
